version: '3'

services:
    gallery:
        image: 'bbalbon/trippy_advisors_calendar_widget:gallery'
        depends_on:
            - 'database'
        ports:
            - '6969:6969'

    database:
        image: mongo:latest